src/Entity/Temperature.php
<?php

namespace App\Entity;

use App\Repository\TemperatureRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TemperatureRepository::class)
 * @ORM\Table(name="temperature")
 */
class Temperature
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="float")
     */
    private $value;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $feels_like_value;

    /**
     * @ORM\ManyToOne(targetEntity=TemperatureUnit::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $unit;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getValue(): ?float
    {
        return $this->value;
    }

    public function setValue(float $value): self
    {
        $this->value = $value;

        return $this;
    }

    public function getFeelsLikeValue(): ?float
    {
        return $this->feels_like_value;
    }

    public function setFeelsLikeValue(?float $feels_like_value): self
    {
        $this->feels_like_value = $feels_like_value;

        return $this;
    }

    public function getUnit(): ?TemperatureUnit
    {
        return $this->unit;
    }

    public function setUnit(?TemperatureUnit $unit): self
    {
        $this->unit = $unit;

        return $this;
    }
}

src/Form/TemperatureType.php
<?php

namespace App\Form;

use App\Entity\Temperature;
use App\Entity\TemperatureUnit;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TemperatureType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('value')
            ->add('feels_like_value')
            ->add('unit', EntityType::class, [
                'class' => TemperatureUnit::class,
                'choice_label' => 'unit'
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Temperature::class,
        ]);
    }
}

src/Controller/TemperatureController.php
<?php

namespace App\Controller;

use App\Entity\Temperature;
use App\Form\TemperatureType;
use App\Repository\TemperatureRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/temperature")
 */
class TemperatureController extends AbstractController
{
    /**
     * @Route("/", name="temperature_index", methods={"GET"})
     */
    public function index(TemperatureRepository $temperatureRepository): Response
    {
        return $this->render('temperature/index.html.twig', [
            'temperatures' => $temperatureRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="temperature_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $temperature = new Temperature();
        $form = $this->createForm(TemperatureType::class, $temperature, [
            'validation_groups' => 'new_temperature'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($temperature);
            $entityManager->flush();

            return $this->redirectToRoute('temperature_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('temperature/new.html.twig', [
            'temperature' => $temperature,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="temperature_show", methods={"GET"})
     */
    public function show(Temperature $temperature): Response
    {
        return $this->render('temperature/show.html.twig', [
            'temperature' => $temperature,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="temperature_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Temperature $temperature): Response
    {
        $form = $this->createForm(TemperatureType::class, $temperature, [
            'validation_groups' => 'edit_temperature'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('temperature_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('temperature/edit.html.twig', [
            'temperature' => $temperature,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="temperature_delete", methods={"POST"})
     */
    public function delete(Request $request, Temperature $temperature): Response
    {
        if ($this->isCsrfTokenValid('delete' . $temperature->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($temperature);
            $entityManager->flush();
        }

        return $this->redirectToRoute('temperature_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/temperature/_delete_form.html.twig
<form method="post" action="{{ path('temperature_delete', {'id': temperature.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ temperature.id) }}">
    <button class="btn">Delete</button>
</form>

templates/temperature/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/temperature/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Temperature{% endblock %}

{% block body %}
    <h1>Edit Temperature</h1>

    {{ include('temperature/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('temperature_index') }}">back to list</a>

    {{ include('temperature/_delete_form.html.twig') }}
{% endblock %}

templates/temperature/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Temperature index{% endblock %}

{% block body %}
    <h1>Temperature index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Value</th>
                <th>Feels_like_value</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for temperature in temperatures %}
            <tr>
                <td>{{ temperature.id }}</td>
                <td>{{ temperature.value }}</td>
                <td>{{ temperature.feelsLikeValue }}</td>
                <td>
                    <a href="{{ path('temperature_show', {'id': temperature.id}) }}">show</a>
                    <a href="{{ path('temperature_edit', {'id': temperature.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('temperature_new') }}">Create new</a>
{% endblock %}

templates/temperature/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Temperature{% endblock %}

{% block body %}
    <h1>Create new Temperature</h1>

    {{ include('temperature/_form.html.twig') }}

    <a href="{{ path('temperature_index') }}">back to list</a>
{% endblock %}

templates/temperature/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Temperature{% endblock %}

{% block body %}
    <h1>Temperature</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ temperature.id }}</td>
            </tr>
            <tr>
                <th>Value</th>
                <td>{{ temperature.value }}</td>
            </tr>
            <tr>
                <th>Feels_like_value</th>
                <td>{{ temperature.feelsLikeValue }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('temperature_index') }}">back to list</a>

    <a href="{{ path('temperature_edit', {'id': temperature.id}) }}">edit</a>

    {{ include('temperature/_delete_form.html.twig') }}
{% endblock %}