src/Entity/WeatherStatus.php
<?php

namespace App\Entity;

use App\Repository\WeatherStatusRepository;
use Doctrine\ORM\Mapping as ORM;
use JetBrains\PhpStorm\Pure;

/**
 * @ORM\Entity(repositoryClass=WeatherStatusRepository::class)
 * @ORM\Table(name="weather_status")
 */
class WeatherStatus
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $icon_name;

    /**
     * @ORM\ManyToOne(targetEntity=City::class, inversedBy="weatherStatuses")
     * @ORM\JoinColumn(nullable=false)
     */
    private $city;

    /**
     * @ORM\OneToOne(targetEntity=Temperature::class, cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $temperature;

    /**
     * @ORM\ManyToOne(targetEntity=WindDirection::class)
     */
    private $windDirection;

    /**
     * @ORM\OneToOne(targetEntity=Pressure::class, cascade={"persist", "remove"})
     */
    private $pressure;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(?\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getIconName(): ?string
    {
        return $this->icon_name;
    }

    public function setIconName(?string $icon_name): self
    {
        $this->icon_name = $icon_name;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getTemperature(): ?Temperature
    {
        return $this->temperature;
    }

    public function setTemperature(Temperature $temperature): self
    {
        $this->temperature = $temperature;

        return $this;
    }

    public function getWindDirection(): ?WindDirection
    {
        return $this->windDirection;
    }

    public function setWindDirection(?WindDirection $windDirection): self
    {
        $this->windDirection = $windDirection;

        return $this;
    }

    public function getPressure(): ?Pressure
    {
        return $this->pressure;
    }

    public function setPressure(?Pressure $pressure): self
    {
        $this->pressure = $pressure;

        return $this;
    }

    #[Pure] public function __toString(): string
    {
        return $this->getCity()->getName() . ", " . $this->getTemperature()->getValue() . " " . $this->getTemperature()->getUnit()->getUnit();
    }


}

src/Form/WeatherStatusType.php
<?php

namespace App\Form;

use App\Entity\Pressure;
use App\Entity\WeatherStatus;
use App\Entity\City;
use App\Entity\Temperature;
use App\Entity\WindDirection;
use SebastianBergmann\CodeCoverage\Report\Text;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;


class WeatherStatusType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date')
            ->add('icon_name')
            ->add('city', EntityType::class, [
                'class' => City::class,
                'choice_label' => 'name'
            ])
            ->add('temperature', TemperatureType::class)
            ->add('windDirection', EntityType::class, [
                'class' => WindDirection::class,
                'choice_label' => 'direction'
            ])
            ->add('pressure', PressureType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => WeatherStatus::class,
        ]);
    }
}

src/Controller/WeatherStatusController.php
<?php

namespace App\Controller;

use App\Entity\WeatherStatus;
use App\Form\WeatherStatusType;
use App\Repository\CityRepository;
use App\Repository\WeatherStatusRepository;
use App\Service\WeatherUtil;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

/**
 * @Route("/weather/status")
 */
class WeatherStatusController extends AbstractController
{

    /**
     * @Route("/", name="weather_status_index", methods={"GET"})
     */
    public function index(WeatherStatusRepository $weatherStatusRepository): Response
    {
        return $this->render('weather_status/index.html.twig', [
            'weather_statuses' => $weatherStatusRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="weather_status_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $weatherStatus = new WeatherStatus();
        $form = $this->createForm(WeatherStatusType::class, $weatherStatus, [
            'validation_groups' => 'new_weather_status'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($weatherStatus);
            $entityManager->flush();

            return $this->redirectToRoute('weather_status_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('weather_status/new.html.twig', [
            'weather_status' => $weatherStatus,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="weather_status_show", methods={"GET"})
     */
    public function show(WeatherStatus $weatherStatus): Response
    {
        return $this->render('weather_status/show.html.twig', [
            'weather_status' => $weatherStatus,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="weather_status_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, WeatherStatus $weatherStatus): Response
    {
        $form = $this->createForm(WeatherStatusType::class, $weatherStatus, [
            'validation_groups' => 'edit_weather_status'
        ]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('weather_status_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('weather_status/edit.html.twig', [
            'weather_status' => $weatherStatus,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="weather_status_delete", methods={"POST"})
     */
    public function delete(Request $request, WeatherStatus $weatherStatus): Response
    {
        if ($this->isCsrfTokenValid('delete' . $weatherStatus->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($weatherStatus);
            $entityManager->flush();
        }

        return $this->redirectToRoute('weather_status_index', [], Response::HTTP_SEE_OTHER);
    }


    public function cityAction($cityName, WeatherUtil $weatherUtil): Response
    {
        $weatherStatuses = $weatherUtil->getWeatherStatusByCityName($cityName);
        $city = $weatherUtil->getCityByName($cityName);

        return $this->render('weather_status/city.html.twig', [
            'location' => $city,
            'weatherStatuses' => $weatherStatuses,
        ]);
    }


    public function getCityByLocation($location, WeatherUtil $weatherUtil): Response
    {
        $weatherStatuses = $weatherUtil->getWeatherStatusByLocation($location);
        $city = $weatherUtil->getCityByLocation($location);

        return $this->render('weather_status/city.html.twig', [
            'location' => $city,
            'weatherStatuses' => $weatherStatuses,
        ]);
    }
}

templates/weather_status/_delete_form.html.twig
<form method="post" action="{{ path('weather_status_delete', {'id': weather_status.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ weather_status.id) }}">
    <button class="btn">Delete</button>
</form>

templates/weather_status/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/weather_status/city.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello WeatherStatusController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper {
            margin: 1em auto;
            max-width: 800px;
            width: 95%;
            font: 18px/1.5 sans-serif;
        }

        .example-wrapper code {
            background: #F5F5F5;
            padding: 2px 6px;
        }
    </style>

    <div class="example-wrapper">
        <h1>Hello {{ location.name }}! ✅</h1>

        <ul>
            {% for measurement in weatherStatuses %}
                <li>{{ measurement.date|date('d.m.Y') }}
                    : {{ measurement.temperature.value }} {{ measurement.temperature.unit.unit }}
                    , feels
                    like {{ measurement.temperature.getFeelsLikeValue() }} {{ measurement.temperature.unit.unit }}
                    : {{ measurement.pressure.value }} {{ measurement.pressure.getPressureUnit().getUnit() }}
                    : wind direction {{ measurement.getWindDirection().getDirection() }}

                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

templates/weather_status/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit WeatherStatus{% endblock %}

{% block body %}
    <h1>Edit WeatherStatus</h1>

    {{ include('weather_status/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('weather_status_index') }}">back to list</a>

    {{ include('weather_status/_delete_form.html.twig') }}
{% endblock %}

templates/weather_status/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}WeatherStatus index{% endblock %}

{% block body %}
    <h1>WeatherStatus index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Date</th>
                <th>Icon_name</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for weather_status in weather_statuses %}
            <tr>
                <td>{{ weather_status.id }}</td>
                <td>{{ weather_status.date ? weather_status.date|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ weather_status.iconName }}</td>
                <td>
                    <a href="{{ path('weather_status_show', {'id': weather_status.id}) }}">show</a>
                    <a href="{{ path('weather_status_edit', {'id': weather_status.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('weather_status_new') }}">Create new</a>
{% endblock %}

templates/weather_status/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New WeatherStatus{% endblock %}

{% block body %}
    <h1>Create new WeatherStatus</h1>

    {{ include('weather_status/_form.html.twig') }}

    <a href="{{ path('weather_status_index') }}">back to list</a>
{% endblock %}

templates/weather_status/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}WeatherStatus{% endblock %}

{% block body %}
    <h1>WeatherStatus</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ weather_status.id }}</td>
            </tr>
            <tr>
                <th>Date</th>
                <td>{{ weather_status.date ? weather_status.date|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Temperature</th>
                <td>{{ weather_status.temperature.value }} {{ weather_status.temperature.unit.unit }}</td>
            </tr>
            <tr>
                <th>Pressure</th>
                <td>{{ weather_status.pressure.value }} {{ weather_status.pressure.getPressureUnit.unit }}</td>
            </tr>
            <tr>
                <th>Wind direction</th>
                <td>{{ weather_status.getWindDirection.direction }}</td>
            </tr>
            <tr>
                <th>Icon_name</th>
                <td>{{ weather_status.iconName }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('weather_status_index') }}">back to list</a>

    <a href="{{ path('weather_status_edit', {'id': weather_status.id}) }}">edit</a>

    {{ include('weather_status/_delete_form.html.twig') }}
{% endblock %}